version: 1.0.0

components:
  - name: my-express-app
    type: service
    runtime: nodejs14
    source:
      type: local
      path: .
    env:
      - name: PORT
        value: "3000"
    ports:
      - port: 3000
        protocol: HTTP
