apiVersion: choreo.io/v1
kind: Endpoint
metadata:
  name: lotf
spec:
  type: http
  resources:
    - path: .
      method: GET
      operationId: getHello
      responses:
        200:
          description: A simple hello world message
          content:
            application/json:
              example: |
                { "message": "Hello, world!" }
    - path: .
      method: POST
      operationId: postGreet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: A greeting message
          content:
            application/json:
              example: |
                { "message": "Hello, <name>!" }
